#Этот файл содержит конфигурацию докер контейнеров для
#database - база данных postgresql
#questions-api - API

version: "3"
services:
  database:
    image: postgres
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=questions-api-db #Эта переменная задаёт имя базы данных
      - POSTGRES_USER=testuser #Эта переменная создаёт суперпользователя с указанным именем
      - POSTGRES_PASSWORD=12345 #ВАЖНО! Это пароль суперпользователя базы данных. Это значение нужно изменить перед запуском бд
    ports:
      - 5432:5432