#Этот файл содержит конфигурацию докер контейнеров для
#database - база данных postgresql
#questions-api - API

version: "3"
services:
  app: 
    build: .
    environment:
      - ADDRESS=0.0.0.0 #Адрес, по которому доступно приложение
      - PORT=8000 #порт, на котором хранится приложение
      - DEBUG=True #ФЛаг позволяет включить дополнительные возможно для отладки.
      - RELOAD=True #Флаг позволяет включить автоматическую перезагрузку сервера при изменении исходного кода.
    ports:
      - 8000:8000
    volumes:
      - ./infrastructure:/app/infrastructure
      #... #Здесь можно добавлять папки, содержащие исходники для быстрого обновления контейнера
  database:
    image: postgres
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=questions-api-db #Эта переменная задаёт имя базы данных
      - POSTGRES_USER=testuser #Эта переменная создаёт суперпользователя с указанным именем
      - POSTGRES_PASSWORD=12345 #ВАЖНО! Это пароль суперпользователя базы данных. Это значение нужно изменить перед запуском бд
    ports:
      - 5432:5432