"""empty message

Revision ID: 446124947268
Revises: 
Create Date: 2023-10-19 07:00:31.814541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '446124947268'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('api_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    #Следующий код добавлен вручную для подстройки миграции
    op.execute('UPDATE questions SET api_id = id')
    op.drop_column("questions", "id")
    op.add_column('questions', sa.Column('id', sa.Integer, primary_key=True, autoincrement=True))



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'api_id')
    # ### end Alembic commands ###
